# Init completions
autoload -Uz compinit
compinit

zstyle ':completion:*' menu select

# Enable starship prompt
eval "$(starship init zsh)"

# Add Applications/bin to path
export PATH="$PATH:/home/danny/Applications/bin"

# Shared aliases
[[ -f $HOME/.aliases ]] &&  . $HOME/.aliases

# Personal aliases
[[ -f $HOME/.zshrc-personal ]] && . $HOME/.zshrc-personal

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/danny/Applications/google-cloud-sdk/path.zsh.inc' ]; then . '/home/danny/Applications/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/danny/Applications/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/danny/Applications/google-cloud-sdk/completion.zsh.inc'; fi

## History file configuration
[ -z "$HISTFILE" ] && HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=10000

## History command configuration
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt inc_append_history     # add commands to HISTFILE in order of execution
setopt share_history          # share command history data

# Check for dircolors
#[[ -r "~/.dir_colors" ]] && eval $(dircolors ~/.dir_colors)

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/danny/.sdkman"
[[ -s "/home/danny/.sdkman/bin/sdkman-init.sh" ]] && source "/home/danny/.sdkman/bin/sdkman-init.sh"
